FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    python3 python3-pip git curl ca-certificates \
  && ln -sf /usr/bin/python3 /usr/bin/python \
  && ln -sf /usr/bin/pip3     /usr/bin/pip \
  && rm -rf /var/lib/apt/lists/*

ENV PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt requirements.txt
COPY requirements.cpu.txt requirements.cpu.txt

RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir -r requirements.cpu.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
