FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements.txt
COPY requirements.cpu.txt requirements.cpu.txt

RUN pip install --upgrade pip && pip install -r requirements.txt && pip install -r requirements.cpu.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
