from datetime import datetime

SHORT_MEMOS = [
    {
        "title": "メモ1",
        "user_id": "a",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [0.1] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
    {
        "title": "メモ2",
        "user_id": "a",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [0.1] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
    {
        "title": "Memo 3",
        "user_id": "b",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [0.1] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
    {
        "title": "Memo 4",
        "user_id": "a",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [0.1] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
]

LONG_MEMOS = [
    {
        "title": "メモ1",
        "user_id": "a",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [0.1] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
    {
        "title": "メモ2",
        "user_id": "a",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [0.2] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
    {
        "title": "メモ3",
        "user_id": "a",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [0.2] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
    {
        "title": "メモ4",
        "user_id": "a",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [0.2] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
    {
        "title": "メモ5",
        "user_id": "a",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [0.2] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
    {
        "title": "メモ6",
        "user_id": "a",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [-0.2] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
    {
        "title": "メモ7",
        "user_id": "a",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [1.0] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
    {
        "title": "メモ8",
        "user_id": "b",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [0.0] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
    {
        "title": "メモ9",
        "user_id": "b",
        "body": "sample",
        "raw": "sample",
        "is_favorite": False,
        "is_archive": False,
        "simple_embedding": [0.0] * 3,
        "created_at": datetime(2024, 4, 1, 15, 30, 0),
        "updated_at": datetime(2024, 4, 9, 15, 30, 0),
    },
]

EMPTY_MEMOS = []
