"""Update Tables

Revision ID: 00ae4b6890fb
Revises: 765e24a26d0c
Create Date: 2025-05-26 14:51:16.785680

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00ae4b6890fb"
down_revision: Union[str, None] = "765e24a26d0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memo_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False
        ),
        sa.ForeignKeyConstraint(["id"], ["memos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "memos",
        sa.Column(
            "simple_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=3), nullable=False
        ),
    )
    op.add_column("memos", sa.Column("is_archive", sa.Boolean(), nullable=False))
    op.add_column("memos", sa.Column("archived_at", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memos", "archived_at")
    op.drop_column("memos", "is_archive")
    op.drop_column("memos", "simple_embedding")
    op.drop_table("memo_embeddings")
    # ### end Alembic commands ###
