"""Add CASCADE

Revision ID: 32dd28db5105
Revises: 801604a2af06
Create Date: 2025-05-23 17:05:00.645156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32dd28db5105'
down_revision: Union[str, None] = '801604a2af06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('memotags_tag_id_fkey'), 'memotags', type_='foreignkey')
    op.drop_constraint(op.f('memotags_memo_id_fkey'), 'memotags', type_='foreignkey')
    op.create_foreign_key(None, 'memotags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'memotags', 'memos', ['memo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memotags', type_='foreignkey')
    op.drop_constraint(None, 'memotags', type_='foreignkey')
    op.create_foreign_key(op.f('memotags_memo_id_fkey'), 'memotags', 'memos', ['memo_id'], ['id'])
    op.create_foreign_key(op.f('memotags_tag_id_fkey'), 'memotags', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
