"""Restore tag_embeddings table

Revision ID: 49686b294915
Revises: 9e2f0c00a897
Create Date: 2025-05-27 15:21:59.626632

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49686b294915"
down_revision: Union[str, None] = "9e2f0c00a897"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("raw", sa.String(), nullable=False),
        sa.Column(
            "simple_embedding", pgvector.sqlalchemy.vector.VECTOR(dim=3), nullable=False
        ),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("is_archive", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "memo_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False
        ),
        sa.ForeignKeyConstraint(["id"], ["memos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "memotags",
        sa.Column("memo_tag_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("memo_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["memo_id"], ["memos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("memo_tag_id"),
    )
    op.create_table(
        "tag_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False
        ),
        sa.ForeignKeyConstraint(["id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tag_embeddings")
    op.drop_table("memotags")
    op.drop_table("memo_embeddings")
    op.drop_table("tags")
    op.drop_table("memos")
    # ### end Alembic commands ###
