"""Update Tag Table

Revision ID: 801604a2af06
Revises: 247e0ab9518d
Create Date: 2025-05-22 09:12:57.371956

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "801604a2af06"
down_revision: Union[str, None] = "247e0ab9518d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "tags", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tags", type_="unique")
    # ### end Alembic commands ###
