"""Add raw column

Revision ID: a643ad12cf50
Revises: d300c6ec5e90
Create Date: 2025-05-20 07:38:00.693403

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a643ad12cf50"
down_revision: Union[str, None] = "d300c6ec5e90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memos", sa.Column("raw", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memos", "raw")
    # ### end Alembic commands ###
